book_rental_app/urls.py
from django.urls import path
from . import views
app_name = 'book_rental_app'

urlpatterns = [
    # LOGIN_REDIRECT_URL
    path('index/', views.index, name='index'),

    # 管理者
    path('index_lender/', views.index_lender, name='index_lender'),
    path('list_large_category/', views.list_large_category, name='list_large_category'),
    path('create_large_category/', views.create_large_category, name='create_large_category'),
    path('list_small_category/<int:pk>/', views.list_small_category, name='list_small_category'),
    path('create_small_category/<int:pk>/', views.create_small_category, name='create_small_category'),

    path('select_large_category/', views.select_large_category, name='select_large_category'),
    path('select_small_category/<int:large_pk>/', views.select_small_category, name='select_small_category'),
    path('add_book/<int:large_pk>/<int:small_pk>/', views.add_book, name='add_book'),
    path('add_book_confirm/<int:pk>/', views.add_book_confirm, name='add_book_confirm'),

    path('list_books', views.list_books, name='list_books'),

    path('index_status/', views.index_status, name='index_status'),
    path('list_status/', views.list_status, name='list_status'),
    path('list_status_user/', views.list_status_user, name='list_status_user'),
    path('detail_status_user/<int:pk>/', views.detail_status_user, name='detail_status_user'),
    path('history_status_user/<int:pk>/', views.history_status_user, name='history_status_user'),

    # 利用者
    path('index_borrower/', views.index_borrower, name='index_borrower'),

    path('list_borrowing/', views.list_borrowing, name='list_borrowing'),
    path('permission_borrowing/', views.permission_borrowing, name='permission_borrowing'),
    path('confirm_borrowing/', views.confirm_borrowing, name='confirm_borrowing'),

    path('list_borrowed/', views.list_borrowed, name='list_borrowed'),
    path('list_returning/', views.list_returning, name='list_returning'),
    path('confirm_returning/', views.confirm_returning, name='confirm_returning'),

    path('rental_history/', views.rental_history, name='rental_history'),

]

book_rental_dev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('register.urls')),
    path('', include('book_rental_app.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル

    usernameを使わず、emailアドレスをユーザー名として使うようにしています。

    """
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    """
    5冊目での貸出上限フラグ追加
    """
    rental_limit = models.BooleanField(default=False, help_text='5冊以上借りたらTrue', verbose_name='貸出上限フラグ')
    """
    借りているかどうかでフラグ追加
    """
    is_borrowing = models.BooleanField(default=False, help_text='本を借りていればTrue', verbose_name='本を借りている人/is_borrowing')

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email

    def __str__(self):
        return self.last_name + self.first_name + ':' + self.email

register/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model

User = get_user_model()


class EmailChangeForm(forms.ModelForm):
    """メールアドレス変更フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        fields = ('last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, EmailChangeForm
)


User = get_user_model()


class Top(generic.TemplateView):
    template_name = 'register/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # まだ仮登録で、他に問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スーパーユーザーだけユーザーページアクセスを許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    """ユーザーの詳細ページ"""
    model = User
    template_name = 'register/user_detail.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新ページ"""
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'  # デフォルトユーザーを使う場合に備え、きちんとtemplate名を書く

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }

        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

register/templates/register/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>書籍管理</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/borrower.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
        {% comment %} history.htmlにおいて、テーブルの行選択の中にプルダウン設置有効化のために以下配置 {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% block head %}
        {% endblock %}
        
        <title>{% block title%}{% endblock %}</title>
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                <a class="navbar-brand" href="{% url 'book_rental_app:index_lender' %}">書籍管理</a>
                {% else %}
                <a class="navbar-brand" href="{% url 'book_rental_app:index_borrower' %}">書籍管理</a>
                {% endif %}
                {% else %}
                <a class="navbar-brand" href="{% url 'register:login' %}">書籍管理</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        {% if user.is_authenticated %}
                        {% if user.last_name and user.first_name %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                            href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.last_name }}{{ user.first_name }}</a>
                            <div class="dropdown-menu left">
                            <a class="dropdown-item" href="{% url 'register:user_detail' user.pk %}">ユーザー情報</a>
                            <a class="dropdown-item" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
                            <a class="dropdown-item" href="{% url 'register:password_change' %}">パスワード変更</a>
                            <a class="dropdown-item" href="{% url 'register:email_change' %}">メールアドレス変更</a>
                            <a class="dropdown-item" href="{% url 'register:logout' %}">LOGOUT</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                            href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            アカウント</a>
                            <div class="dropdown-menu left">
                            <a class="dropdown-item" href="{% url 'register:user_detail' user.pk %}">ユーザー情報</a>
                            <a class="dropdown-item" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
                            <a class="dropdown-item" href="{% url 'register:password_change' %}">パスワード変更</a>
                            <a class="dropdown-item" href="{% url 'register:email_change' %}">メールアドレス変更</a>
                            <a class="dropdown-item" href="{% url 'register:logout' %}">LOGOUT</a>
                            </div>
                        </li>
                        {% endif %}
                        {% else %}
                        <div class="collapse navbar-collapse justify-content-end">
                        <ul class="nav navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'register:login' %}">LOGIN</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'register:user_create' %}">SIGNUP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">　</a>
                        </li>
                        </ul>
                        </div>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav> 
        <section>
        {% block header %}
        {% endblock %}
        {% block content %}
        {% endblock %}
        <section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

register/templates/register/email_change_done.html
{% extends "register/base.html" %}
{% block title%}メールアドレス変更{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>メールアドレス変更</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
<p>
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
</div>
{% endblock %}

register/templates/register/email_change_form.html
{% extends "register/base.html" %}
{% block title%}メールアドレス変更{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>メールアドレス変更</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
</div>
{% endblock %}

register/templates/register/login.html
{% extends "register/base.html" %}
{% block title%}ログイン{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>ログイン</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
<div class="row">
    <!-- 左側、ログインエリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <form action="{% url 'register:login' %}" method="POST">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </form>
        </div>
    </div><!-- 左側、ログインエリアおわり -->

    <!-- 右側、会員登録エリア -->
    <div class="card col-md-6">
        <div class="card-body">
            <a href="{% url 'register:user_create' %}" class="btn btn-success btn-lg btn-block" >サインアップ</a><hr>
            <a href="{% url 'register:password_reset' %}" class="btn btn-success btn-lg btn-block" >パスワードを忘れた方</a>
        </div>
    </div><!-- 右側、会員登録エリアおわり -->
</div>
</div>
{% endblock %}

register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block title%}パスワード変更{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>パスワード変更</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
</div>
{% endblock %}

register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block title%}パスワード変更{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>パスワード変更</h3>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
<p>
    パスワードを変更しました。<br>
</p>
</div>
{% endblock %}

register/templates/register/password_reset_confirm.html
{% extends "register/base.html" %}
{% block title%}パスワードリセット{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>パスワードリセット</h3>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
</div>
{% endblock %}

register/templates/register/password_reset_done.html
{% extends "register/base.html" %}
{% block title%}パスワードリセット{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>パスワードリセット</h3>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
</div>
{% endblock %}

register/templates/register/top.html
{% extends "register/base.html" %}
{% block title%}ログアウト{% endblock %}

{% block header %}
<div class="container-fluid">
  <h3>ログアウト完了</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
    <p><h3>ログアウトしました。</h3></p>
</div>
    <script>
    setTimeout(function(){
        window.location.href = '{% url 'register:login' %}';
      }, 3*1000);
    </script>

{% endblock %}

register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block title%}サインアップ{% endblock %}

{% block header %}
<div class="container-fluid">
    <h3>サインアップ</h3>
</div>
{% endblock %}

{% block content %}
<br>
<div class="container-fluid">
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
</diV>
{% endblock %}