book_rental_app/urls.py
from django.urls import path
from . import views
app_name = 'book_rental_app'

urlpatterns = [
    # LOGIN_REDIRECT_URL
    path('index/', views.index, name='index'),

    # 管理者
    path('index_lender/', views.index_lender, name='index_lender'),
    path('list_large_category/', views.list_large_category, name='list_large_category'),
    path('create_large_category/', views.create_large_category, name='create_large_category'),
    path('list_small_category/<int:pk>/', views.list_small_category, name='list_small_category'),
    path('create_small_category/<int:pk>/', views.create_small_category, name='create_small_category'),

    path('select_large_category/', views.select_large_category, name='select_large_category'),
    path('select_small_category/<int:large_pk>/', views.select_small_category, name='select_small_category'),
    path('add_book/<int:large_pk>/<int:small_pk>/', views.add_book, name='add_book'),
    path('add_book_confirm/<int:pk>/', views.add_book_confirm, name='add_book_confirm'),

    path('list_books', views.list_books, name='list_books'),

    path('index_status/', views.index_status, name='index_status'),
    path('list_status/', views.list_status, name='list_status'),
    path('list_status_user/', views.list_status_user, name='list_status_user'),
    path('detail_status_user/<int:pk>/', views.detail_status_user, name='detail_status_user'),
    path('history_status_user/<int:pk>/', views.history_status_user, name='history_status_user'),

    # 利用者
    path('index_borrower/', views.index_borrower, name='index_borrower'),

    path('list_borrowing/', views.list_borrowing, name='list_borrowing'),
    path('permission_borrowing/', views.permission_borrowing, name='permission_borrowing'),
    path('confirm_borrowing/', views.confirm_borrowing, name='confirm_borrowing'),

    path('list_borrowed/', views.list_borrowed, name='list_borrowed'),
    path('list_returning/', views.list_returning, name='list_returning'),
    path('confirm_returning/', views.confirm_returning, name='confirm_returning'),

    path('rental_history/', views.rental_history, name='rental_history'),

]

book_rental_dev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('register.urls')),
    path('', include('book_rental_app.urls')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

book_rental_app/forms.py
from django import forms

from register.models import User
from .models import Books, LargeCategory, SmallCategory

class LargeCategoryForm(forms.ModelForm):
    class Meta:
        model = LargeCategory
        fields = '__all__'
        labels = {
            'name': '',
        }


class SmallCategoryForm(forms.ModelForm):
    class Meta:
        model = SmallCategory
        fields = '__all__'
        labels = {
            'large_category': '',
            'name': '',
        }


class BooksForm(forms.ModelForm):
    class Meta:
        model = Books
        fields = '__all__'
        labels = {
            'manage_id': '',
            'id_in_category': '',
            'title': '',
            'category': '',
            'borrower_user': '',
            'lender_user': '',
            'is_rental': '',
        }



class LenderForm(forms.Form):
    lender = forms.ModelChoiceField(User.objects.filter(is_superuser=True),  label='', empty_label='選択してください', to_field_name='pk', required=True)

book_rental_app/views/books_views.py
from django.shortcuts import render

from book_rental_app.models import LargeCategory, SmallCategory, Books

def select_large_category(request):
    large_categories = LargeCategory.objects.all()
    context = {
        'large_categories': large_categories,
    }
    return render(request, 'lender/add_book/select_large_category.html', context)

def select_small_category(request, large_pk):
    large_category = LargeCategory.objects.get(id=large_pk)
    small_categories = SmallCategory.objects.all()
    context = {
        'large_category': large_category,
        'small_categories': small_categories, 
    }
    return render(request, 'lender/add_book/select_small_category.html', context)

def add_book(request, large_pk, small_pk):
    large_category = LargeCategory.objects.get(id=large_pk)
    small_category = SmallCategory.objects.get(id=small_pk)
    context = {
        'large_category': large_category,
        'small_category': small_category,
    }
    return render(request, 'lender/add_book/add_book.html', context)


def add_book_confirm(request, pk):
    if request.method == 'POST':
        small_category = SmallCategory.objects.get(id=pk)
        manage_id = request.POST.get('manage_id')
        id_in_category = request.POST.get('id_in_category')
        title = request.POST.get('title')
        Books.objects.create(manage_id=manage_id, id_in_category=id_in_category, title=title
                            ,category=small_category)
    return render(request, 'lender/add_book/add_book_confirm.html')

def list_books(request):
    books = Books.objects.all()
    context = {
        'books': books,
    }
    return render(request, 'lender/list_books/list_books.html', context)

book_rental_app/views/borrower_views.py
from django.shortcuts import render, redirect
from book_rental_app.forms import LenderForm
from register.models import User
from book_rental_app.models import Books, LendingStatus
from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta
import datetime as dt
from django.contrib import messages
# Create your views here.

def index_borrower(request):
    return render(request, 'borrower/index.html')


"""
貸出
"""
def list_borrowing(request):
    books = Books.objects.all().order_by('manage_id')
    user = request.user
    print()
    print('borrowing_books:', end='')
    print(user.borrowing_books.all())
    print('len(borrowing_books):', end='')
    print(len(user.borrowing_books.all()))
    total_borrowing = len(user.borrowing_books.all())

    context = {
        'books': books,
        'total_borrowing': total_borrowing,
    }
    return render(request, 'borrower/list_borrowing.html', context)

def permission_borrowing(request):
    if request.method == 'POST':
        #次のページ"confirm_borrowing"に反映させるための構え
        borrowing_books = request.POST.getlist('borrowing_books')
        """
        本を何も選択しなければ
        """
        if len(borrowing_books) == 0:
            messages.warning(request, '本を選んでください。')
            return redirect('book_rental_app:list_borrowing')
        print()
        print('borrowing_books:', end='')
        print(borrowing_books)
        books = []
        for i in borrowing_books:
            books.append(Books.objects.get(id=i))
        form = LenderForm()
        print('form:', end='')
        print(form)
        try:
            context = {
                'books': books,
                'form': form,
            }
            print('books:', end='')
            print(books)
            return render(request, 'borrower/permission_borrowing.html', context)
        except:
            return redirect('book_rental_app:list_borrowing')
        
        

def confirm_borrowing(request):
    if request.method == 'POST':
        # データベース反映の為の下準備と、ページ表示のための処理
        books_ids = request.POST.getlist('books')
        print('books_ids:', end='')
        print(books_ids)


        books_list = []
        for i in books_ids:
            books_list.append(Books.objects.get(id=i))
        print('books:', end='')
        print(books_list)


        """
        担当者を何も選択しなければ
        """
        if request.POST.get('lender') == "":
            form = LenderForm()
            context = {
                'books': books_list,
                'form': form,
            }
            messages.error(request, '担当者を選択してください')
            # return redirect('book_rental_app:list_borrowing')
            return render(request, 'borrower/permission_borrowing.html', context)
        else:
            lender_pk = request.POST.get('lender')
            print('lender_pk:', end='')
            print(lender_pk)
            lender_user = User.objects.get(id=lender_pk)
            print('lender_user:', end='')
            print(lender_user)
       


        # ここからデータベースへの反映処理
        borrower_user = request.user
        # Booksへの反映
        for book in books_list:
            # if book.lendingstatus_set.filter(is_returned=False):
            if book.is_rental:
                print('book.lendingstatus_selt.filter(is_returned=False:', end='')
                print(book.lendingstatus_set.filter(is_returned=False))
                messages.error(request, f'選択した本『{book.title}』が貸し出されてしまいました。もう一度やり直してください。')
                return redirect('book_rental_app:list_borrowing')
                # 上の行が無かった時の挙動で、同時に借りて、返却できた人と出来なかった人の違いは、
                # 先に借りた方が返却出来なくて、後で借りた人が返却できたということ。
            else:
                book.borrower_user = borrower_user
                book.lender_user = lender_user
                book.is_rental = True
                book.save()

        # LendignStatusへの反映
        for book in books_list:
            # if book.lendingstatus_set.filter(is_returned=False):
            # if book.is_rental:
            #     print('book.lendingstatus_selt.filter(is_returned=False:', end='')
            #     print(book.lendingstatus_set.filter(is_returned=False))
            #     messages.error(request, f'選択した本『{book.title}』が貸し出されてしまいました。もう一度やり直してください。')
            #     return redirect('book_rental_app:list_borrowing')
            # else:
            LendingStatus.objects.create(book=book, borrower_user=borrower_user, lender_user=lender_user)
        # Userのrental_limitの確認
        user_books = Books.objects.filter(borrower_user=borrower_user)
        if len(user_books) == 5:
            borrower_user.rental_limit = True
        if borrower_user.is_borrowing == False:
            borrower_user.is_borrowing = True
            borrower_user.save()


        context = {
            'books_list': books_list,
            'lender_user': lender_user
        }
        return render(request, 'borrower/confirm_borrowing.html', context)
    
"""
返却
"""
def list_borrowed(request):
    user = request.user
    borrowed_books = user.borrowing_books.all()
    print('borrowed_books:', end='')
    print(borrowed_books)
    borrowed_books_len = len(borrowed_books)
    lending_status = LendingStatus.objects.filter(borrower_user=user)
    context = {
        'lending_status': lending_status,
        'borrowed_books_len': borrowed_books_len,
    }


    return render(request, 'borrower/list_borrowed.html', context)

def list_returning(request):
    if request.method == 'POST':
        returning_status_id = request.POST.getlist('returning_status_id')
        print()
        print('returning_status_id:', end='')
        print(returning_status_id)
        # returning_books = []
        returning_status_list = []
        for i in returning_status_id:
            lendering_status = LendingStatus.objects.get(id=i)
            returning_status_list.append(lendering_status)
            # returning_book = lendering_status.book
            # returning_book.borrower_user.remove()
            # returning_book.lender_user.remove()
            # returning_book.is_retal = False
            # returning_book.save()
            # print(datetime.today())
            # lendering_status.returned_date = datetime.today()
            # lendering_status.is_returned = True
            # lendering_status.save()

            # returning_books.append(returning_book)
            # print(returning_books)
        print()
        print(returning_status_list)

        context = {
            'returning_status_list': returning_status_list,
        }
        return render(request, 'borrower/list_returning.html', context)

def confirm_returning(request):
    if request.method == 'POST':
        returning_user = request.user
        returning_status_id = request.POST.getlist('returning_status_id')
        print()
        print('returning_status_id:', end='')
        print(returning_status_id)
        returned_status_list = []
        for i in returning_status_id:
            lendering_status = LendingStatus.objects.get(id=i)
            lending_user = lendering_status.lender_user
            returning_book = lendering_status.book
            print('returning_user:', end='')
            print(returning_user)
            print('lending_user:', end='')
            print(lending_user)
            print()
            print(returning_user.borrowing_books.all())
            print(lending_user.lending_books.all())
            returning_user.borrowing_books.remove(returning_book, bulk=False)
            lending_user.lending_books.remove(returning_book, bulk=False)
            print()
            print(returning_user.borrowing_books.all())
            print(lending_user.lending_books.all())
            
            # returning_user.save()
            # lending_user.save()
            # returning_user.borrowing_books.remove(returning_book)
            # lending_user.lending_books.remove(returning_book)
            # returning_book.remove(returning_user, bulk=False)
            # returning_book.remove(lending_user, bulk=False)
            # returning_book.save()
            returning_book.is_rental = False
            returning_book.borrower_user = None
            returning_book.lender_user = None
            returning_book.save()
            print(datetime.today())
            
            lendering_status.is_returned = True
            lendering_status.save()
            returned_status_list.append(lendering_status)
        
        # 1人あたりの貸出上限の5冊を必ず下回るのでフラグ変更
        if returning_user.rental_limit == True:
            returning_user.rental_limit = False
            returning_user.save()
        
        borrowing_books = Books.objects.filter(borrower_user = returning_user)
        if len(borrowing_books) == 0:
            returning_user.is_borrowing = False
            returning_user.save()

        context = {
            'returned_status_list': returned_status_list,
        }
        return render(request, 'borrower/confirm_returning.html', context)

"""
履歴機能
"""
def rental_history(request):
    borrower_user = request.user
    status_history = LendingStatus.objects.filter(is_returned=True, borrower_user=borrower_user).order_by('-checkout_date')
    print(status_history)
    context = {
        'status_history': status_history,
    }
    return render(request, 'borrower/rental_history.html', context)

book_rental_app/views/center_views.py
from django.shortcuts import render
from django.shortcuts import redirect

from book_rental_app.models import LargeCategory, SmallCategory
# Create your views here.

def index(request):
    if not request.user.is_superuser:
        return redirect('book_rental_app:index_borrower')
    else:
        return redirect('book_rental_app:index_lender')

def list_large_category(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        if name == '':
            return redirect('book_rental_app:create_large_category')
        else:
            LargeCategory.objects.create(name=name)
        
    large_categories = LargeCategory.objects.all()
    print(large_categories)
    context = {
        'large_categories': large_categories,
    }
    return render(request, 'lender/category/list_large_category.html', context)

def create_large_category(request):
    return render(request, 'lender/category/create_large_category.html')

def list_small_category(request, pk):
    if request.method == 'POST':
        name = request.POST.get('name')
        large_category = LargeCategory.objects.get(id=pk)
        SmallCategory.objects.create(large_category=large_category, name=name)

    large_category = LargeCategory.objects.get(id=pk)
    small_categories = SmallCategory.objects.filter(large_category__id=pk)
    context = {
        'small_categories': small_categories,
        'large_category': large_category,
    }
    return render(request, 'lender/category/list_small_category.html', context)

def create_small_category(request, pk):
    large_category = LargeCategory.objects.get(id=pk)
    context = {
        'large_category': large_category,
    }
    return render(request, 'lender/category/create_small_category.html', context)

book_rental_app/templates/borrower/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>書籍管理</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/borrower.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
        {% comment %} history.htmlにおいて、テーブルの行選択の中にプルダウン設置有効化のために以下配置 {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% block head %}
        {% endblock %}
        
        <title>{% block title%}{% endblock %}</title>
    </head>
    <body oncontextmenu="alert('メニューは非表示にしています！！'); return false;">
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <a class="navbar-brand" href="{% url 'book_rental_app:index_borrower' %}">書籍管理</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        {% if user.is_authenticated %}
                        {% if user.last_name and user.first_name %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                            href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.last_name }}{{ user.first_name }}</a>
                            <div class="dropdown-menu left">
                            <a class="dropdown-item" href="{% url 'register:user_detail' user.pk %}">ユーザー情報</a>
                            <a class="dropdown-item" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
                            <a class="dropdown-item" href="{% url 'register:password_change' %}">パスワード変更</a>
                            <a class="dropdown-item" href="{% url 'register:email_change' %}">メールアドレス変更</a>
                            <a class="dropdown-item" href="{% url 'register:logout' %}">LOGOUT</a>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                            href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            アカウント</a>
                            <div class="dropdown-menu left">
                            <a class="dropdown-item" href="{% url 'register:user_detail' user.pk %}">ユーザー情報</a>
                            <a class="dropdown-item" href="{% url 'register:user_update' user.pk %}">ユーザー情報更新</a>
                            <a class="dropdown-item" href="{% url 'register:password_change' %}">パスワード変更</a>
                            <a class="dropdown-item" href="{% url 'register:email_change' %}">メールアドレス変更</a>
                            <a class="dropdown-item" href="{% url 'register:logout' %}">LOGOUT</a>
                            </div>
                        </li>
                        {% endif %}
                        {% else %}
                        <div class="collapse navbar-collapse justify-content-end">
                        <ul class="nav navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'register:login' %}">LOGIN</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'register:user_create' %}">SIGNUP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link">　</a>
                        </li>
                        </ul>
                        </div>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav> 
        {% block header %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

book_rental_app/templates/borrower/confirm_borrowing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>書籍貸出</title>
  </head>
  <body>
    <h1>下記の書籍を貸し出しました。</h1>
    <h4>許可者：{{ lender_user }}</h4>
    {% for book in books_list %}
    <p>・{{ book.title }}</p>
    {% endfor %}

    <script>
    setTimeout(function(){
        window.location.href = '{% url 'book_rental_app:index_borrower' %}';
      }, 4*1000);
    </script>
  </body>
</html>

book_rental_app/templates/borrower/confirm_returning.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>書籍貸出</title>
  </head>
  <body>
    <h1>下記の書籍を返却しました。</h1>
    <h4>許可者：{{ lender_user }}</h4>
    {% for status in returned_status_list %}
    <p>管理用ID：{{ status.book.manage_id }}</p>
    <p>大カテゴリー：{{ status.book.category.large_category }}　/　小カテゴリー：{{ status.book.category }}</p>
    <p>書名：{{ status.book.title }}</p>
    <p>許可者：{{ status.lender_user }}</p>
    <p>返却期限：{{ status.get_due_date }}</p>
    <p>返却日：{{ status.returned_date }}</p>
    <hr size="10">
    {% endfor %}

    <script>
    setTimeout(function(){
        window.location.href = '{% url 'book_rental_app:list_borrowed' %}';
      }, 4*1000);
    </script>
  </body>
</html>

book_rental_app/templates/borrower/index.html
{% extends 'borrower/base.html' %}
        
        {% block head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet" />
        {% endblock %}
        {% block title%}{% endblock %}
        {% block header %}
        {% endblock %}
        {% comment %} <!-- Header-->
        <header class="py-5">
            <div class="container px-lg-5">
                <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-5 fw-bold">ログイン</h1>
                        <p class="fs-4">一度に5冊まで。返却期限は3ヶ月。</p>
                        <input type="email" name="example1" placeholder="メールアドレス">
                        <input type="password" name="example2" placeholder="パスワード">
                        <a class="btn btn-primary btn-lg" href="#!">log in</a>
                        
                    </div>
                </div>
            </div>
        </header> {% endcomment %}
        {% block content %}
        <!-- Page Content-->
        <section class="pt-4">
            <div class="container px-lg-5">
                <!-- Page Features-->
                <div class="row gx-lg-5">
                    
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <a class="btn btn-primary btn-lg feature  bg-gradient text-white rounded-3 mb-4 mt-n4" href="{% url 'book_rental_app:list_borrowing' %}"><i class="bi bi-book"></i></a>
                                <h2 class="fs-4 fw-bold">本を借りる</h2>
                                <p class="mb-0"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <a class="btn btn-primary btn-lg feature  bg-gradient text-white rounded-3 mb-4 mt-n4" href="{% url 'book_rental_app:list_borrowed' %}"><i class="bi bi-book-half"></i></a>
                                <h2 class="fs-4 fw-bold">本を返却する</h2>
                                <p class="mb-0"></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <a class="btn btn-warning btn-lg feature  bg-gradient text-white rounded-3 mb-4 mt-n4" href="#!"><i class="bi bi-chat-square-heart"></i></a>
                                <h2 class="fs-4 fw-bold">リクエストフォーム</h2>
                                <p class="mb-0">書籍のリクエストはこちらから。</p>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <a class="btn btn-warning btn-lg feature  bg-gradient text-white rounded-3 mb-4 mt-n4" href="#!"><i class="bi bi-gear"></i></a>
                                <h2 class="fs-4 fw-bold">詳細設定</h2>
                                <p class="mb-0">設定の変更はこちら。</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <a class="btn btn-primary btn-lg feature  bg-gradient text-white rounded-3 mb-4 mt-n4" href="{% url 'book_rental_app:rental_history' %}"><i class="bi bi-clock-history"></i></a>
                                <h2 class="fs-4 fw-bold">履歴</h2>
                                <p class="mb-0">借りた履歴</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}

book_rental_app/templates/borrower/list_returning.html
{% extends 'borrower/base.html' %}
{% block head %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
{% endblock %}
{% block content %}

        <!-- Page Content-->
        <section class="pt-4">
          <div class="container">
            <form method="post" action="{% url 'book_rental_app:confirm_returning' %}">
                {% csrf_token %}
                <h3>下記の書籍を返却しますか？</h3>
                {% for status in returning_status_list %}
                <p>・{{ status.book.title }}</p>
                <input type="hidden" value="{{ status.pk }}" name="returning_status_id">
                {% endfor %}
                {% comment %} {{ form }} {% endcomment %}
            {% comment %} <input type="button" onClick="myEnter()" value="返却する"> {% endcomment %}
            <input type="submit" value="返却する">
            </form>
          </div>
        </section>


      <script>
        function myEnter(){
          Input=window.prompt("パスワードを入力してください","");
          if ( Input == "hoge" ) {
          $('form').attr('action', {% url 'book_rental_app:confirm_borrowing' %});
          $('form').submit();
          } else { alert( "パスワードが違います!" );
        }
        }
      </script>
{% endblock %}